server:
  port: 8080


spring:
   #指定配置环境
  profiles:
    active: test
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp

#热部署
devtools:
  restart:
    enabled: true
    #添加那个目录的文件需要restart
    additional-paths: src/main/java
     #排除那个目录的文件不需要restart
    exclude: pages/**

#mybatis:
#  mapper-locations: classpath*:sqlMapper/**/*Mapper.xml